dockstore/lambda

upsertGitHubTag-f79c4f36-3e61-43f4-8f6c-0b2e0e9774d7/deployment/index.js

https://github.com/dockstore/dockstore/issues/2768
Working on a bunch of different scenarios:
* username was incorrect for automatically added repositories (when the github app is added in anticipation of more repos to the whole org)
* when repositories are selected to be added one-by-one in the github app

Working on making service upsert more robust

---

upsertGitHubTag-f79c4f36-3e61-43f4-8f6c-0b2e0e9774d7/deployment/index.js

Now only handle the push webhook (before was install and release endpoints). It simplifies the code a lot.
https://github.com/dockstore/dockstore/issues/2990

Single release endpoint

---

upsertGitHubTag-f79c4f36-3e61-43f4-8f6c-0b2e0e9774d7/deployment/index.js

Handles delete event of a branch/tag from GitHub. Needs to be tested on dev.

Delete version GitHub

---

upsertGitHubTag-f79c4f36-3e61-43f4-8f6c-0b2e0e9774d7/deployment/index.js

Wasn't passing the callback function to the helper function.

pass callback to helper method

---

upsertGitHubTag-f79c4f36-3e61-43f4-8f6c-0b2e0e9774d7/deployment/index.js

use new buffer approach

---

upsertGitHubTag-f79c4f36-3e61-43f4-8f6c-0b2e0e9774d7/deployment/index.js

Read X-GitHub-Event from body map instead of header.

fix github event header

---

upsertGitHubTag-f79c4f36-3e61-43f4-8f6c-0b2e0e9774d7/deployment/index.js

https://github.com/dockstore/dockstore/issues/3611
If contentType is set and is text/plain, return bodyString, else return the status message.

handle null contentType

---

cloud-watch-to-slack-testing-58006136-c30b-43d1-880c-7b36f860e7c8/deployment/index.js

Code constructs an appropriate message about terminal session logins to EC2 instances. 
Requires creating a CloudWatch Rule: 
`
{
"source": [
"aws.ssm"
],
"detail-type": [
"AWS API Call via CloudTrail"
],
"detail": {
"eventSource": [
"ssm.amazonaws.com"
],
"eventName": [
"StartSession",
"ResumeSession",
"TerminateSession"
]
}
}
`
triggered by an SSM event with SNS target: 
- (dev account) slack-dev-testing for Slack channel dockstore-dev-testing
- (production account) slack-low-priority-topic for Slack channel dockstore-testing
Lots of changes needed to other lambdas or may need a new Lambda for sending message to Slack channels dockstore-dev-alerts or dockstore-alerts
Addresses:
https://ucsc-cgl.atlassian.net/browse/SEAB-1395

handle SSM terminal session events

---

upsertGitHubTag-f79c4f36-3e61-43f4-8f6c-0b2e0e9774d7/deployment/index.js

Main issue: https://ucsc-cgl.atlassian.net/browse/SEAB-1680
Sibling PRs: https://github.com/dockstore/dockstore-deploy/pull/99 #19 
Consolidate base64 GitHub payload decoding in lambda

Remove repeat base64 decodes

---

.github/dependabot.yml

Will need to figure out syntax for nested lambdas

Ensure dependabot understands root

---

cloud-watch-to-slack-testing-58006136-c30b-43d1-880c-7b36f860e7c8/deployment/index.js

Addresses Alert when root logs into AWS https://ucsc-cgl.atlassian.net/browse/SEAB-2233
Will look like this in Slack:
Related to PR: https://github.com/dockstore/dockstore-deploy/pull/198

add code to notify on root login

---

cloud-watch-to-slack-testing-58006136-c30b-43d1-880c-7b36f860e7c8/deployment/index.js

Addresses: https://ucsc-cgl.atlassian.net/browse/SEAB-2063

Send GuardDuty Findings to slack

---

cloud-watch-to-slack-testing-58006136-c30b-43d1-880c-7b36f860e7c8/deployment/index.js

Addresses https://ucsc-cgl.atlassian.net/browse/SEAB-2224

send trusted advisor events to slack

---

cloud-watch-to-slack-testing-58006136-c30b-43d1-880c-7b36f860e7c8/deployment/index.js

Addresses https://ucsc-cgl.atlassian.net/browse/SEAB-2903
Related to https://github.com/dockstore/dockstore-deploy/pull/244

Read mapping of SNS topic resource ids to determine Slack channel

---

.husky/commit-msg
.husky/pre-commit
.husky/prepare-commit-msg
package-lock.json
package.json

Migrate to Husky 7

---

.circleci/config.yml

https://ucsc-cgl.atlassian.net/browse/SEAB-2852
For now, builds will continue to use env variables defined at the project
level, but once we clear those, they will fall back on this context.

Get ready to use CircleCI context

---

.circleci/config.yml

Email from circle-ci noted this repo
https://circleci.com/blog/announcing-our-next-generation-convenience-images-smaller-faster-more-deterministic

circle-ci recommendation

---

cloud-watch-to-slack-testing/deployment/index.js

Thanks @amarjandu , log message was on the wrong line

Fix logging

---

cloud-watch-to-slack-testing/deployment/index.js

[SEAB-4264](https://ucsc-cgl.atlassian.net/browse/SEAB-4264)
The corresponding dockstore-deploy PR is https://github.com/dockstore/dockstore-deploy/pull/498
This PR formats messages for ECS auto scaling and CloudWatch alarm state change events from Event Bridge.

Add ECS auto scaling message

---

.github/PULL_REQUEST_TEMPLATE.md
nextflow-parsing/NextflowParsingFunction/pom.xml

Add PR template.
Needed for https://ucsc-cgl.atlassian.net/browse/SEAB-4603
The openapi-java-client version artifact was no longer on artifactory, so updated the version. Discussed [here](https://app.slack.com/archives/C16ET3CF4/p1658531381120469).

Feature/seab 4603/betterprtemplate
