upsertGitHubTag-f79c4f36-3e61-43f4-8f6c-0b2e0e9774d7/deployment/index.js

Seems like there were some events that were getting through causing errors that we don't care about (ex. repository installs). Now we check for specific fields, and if any are missing we return success (so that lambda doesn't retry) and print a message saying unsupported.

handle events that are not supported

---

upsertGitHubTag-f79c4f36-3e61-43f4-8f6c-0b2e0e9774d7/deployment/index.js

Main issue: https://ucsc-cgl.atlassian.net/browse/SEAB-1692
Sibling PR: https://github.com/dockstore/dockstore-deploy/pull/118
I'm hoping to leverage Lambda's built-in `Errors` metric to set up alarms for our GitHub Apps Lambda. But we don't want 4XX responses like 418 to show as errors (since they are easily caused by tags/branches without `.dockstore.yml`).
Changing this to an `INFO` log makes the `Errors` metric perfect for our intended use.
More info in these comments: https://ucsc-cgl.atlassian.net/browse/SEAB-1692?focusedCommentId=31853

change console.error to console.info to avoid AWS Lambda Errors

---

.github/workflows/maven.yml
cloud-watch-to-slack-testing-58006136-c30b-43d1-880c-7b36f860e7c8/deployment/index.js

This PR introduces code to send messages to Slack for dev, staging and prod. The lambda is different from what is currently on dev.dockstore.net in that this staging code uses AWS managed keys to encrypt the environment variables at rest instead of using a customer managed key. This simplifies the code. It's unclear to me why we need to use a customer managed key.
Strangely, the lambda currently on dev.dockstore.net handles mail attachments; but that is not reflected in the lambda code checked in here for develop. It's not clear to me if this code is needed.
Additionally, there are output-template.yml, template.yml files that do not match this new index.js code with respect to the AWS managed key use. It's unclear to me how these are generated.
This code is enabled with the CloudFormation …

Code for dev, staging and prod AWS SSM and AWS config lambda

---

upsertGitHubTag-f79c4f36-3e61-43f4-8f6c-0b2e0e9774d7/deployment/index.js

https://ucsc-cgl.atlassian.net/browse/SEAB-2511
We could also use an accept browser user-agent. For now, this seems the most explicit.

Added user-agent headers

---

.circleci/config.yml
cloud-watch-to-slack-testing-58006136-c30b-43d1-880c-7b36f860e7c8/deployment/index.js
package.json

Part of work for https://ucsc-cgl.atlassian.net/browse/SEAB-2276
The deployer will publish messages to SNS (work in progress in dockstore-deploy). The deployer will set the source to `dockstore.deployer`.
This PR enables the lambda to process such events.
As part of this, broke the code up into several functions to make it more readable, at least for me.
Also added linting as for this one lambda. There are other lambdas in the repo, but I was only working
on this one.  One step at a time.

Support Deployer Notifications

---

checkUrlExists/events/event.json
package-lock.json
package.json
upsertGitHubTag-f79c4f36-3e61-43f4-8f6c-0b2e0e9774d7/deployment/index.js
upsertGitHubTag-f79c4f36-3e61-43f4-8f6c-0b2e0e9774d7/deployment/index.spec.js

For https://ucsc-cgl.atlassian.net/browse/SEAB-3009
Should render all dependabot PRs useless
Husky is only updated to v4 instead of v6 because it has breaking changes. Splitting that out for security people to do. Moved husky to dev deps while i was at it.
Created https://github.com/dockstore/dockstore/issues/4281

Feature/seab 3009/dep update

---

cloud-watch-to-slack-testing-58006136-c30b-43d1-880c-7b36f860e7c8/deployment/index.js

Addresses https://ucsc-cgl.atlassian.net/browse/SEAB-2769
Changes to CloudTrail only capture object events for bucket oicr.dockstore.backups 
Related to https://github.com/dockstore/dockstore-deploy/pull/275

capture s3 events and output msg

---

nextflow-parsing/NextflowParsingFunction/src/test/java/io/dockstore/nextflowparsing/AppTest.java

Modify the test so that it should also work for Mac. Someone with a mac needs to test this:
Don't use sam build --use-container to test, it runs in its own container
This is the Nextflow parsing lambda tests

Modify test for Mac

---

.circleci/config.yml
wdl-parsing/WDLParsingFunction/pom.xml

more https://ucsc-cgl.atlassian.net/browse/SEAB-4284
on merge, will deactivate keys in old context
--------------------
separately, looks like broad has deleted an old dependency so I had to upload it to artifacts to get the build to pass

switch to openid connect

---

cloud-watch-to-slack-testing/deployment/index.js

This is a change to support sending simple unstructured messages via SNS that can appear in slack. In this case, an SSM automation prepares the content of the message instead of requiring the lambda to format a slack readable message.
Used by an SSM document to be added at dockstore-deploy https://github.com/dockstore/dockstore-deploy/pull/481. This change is currently in test in dev.
https://ucsc-cgl.atlassian.net/browse/SEAB-3465

Allow simple unstructured slack messages

---

upsertGitHubTag/deployment/index.js

This PR fixes the strange behavior that was reported in https://ucsc-cgl.atlassian.net/browse/DOCK-2126 dockstore/dockstore#4831.
TLDR: The lambda was not retrying requests when it received a 5xx from the webservice, causing pushes to be lost.  This PR fixes it.  And it's a negative-one-liner w00t!
A node.js lambda handler method is passed a callback, which is used by the lambda to return a result or signal an error condition:
https://docs.aws.amazon.com/lambda/latest/dg/nodejs-handler.html
After much investigation, I determined that the line that I removed was being executed before most other callback invocations, essentially preempting all subsequent retry decisions (most (all?) of which are made in event handlers).  Valid requests were only being retried in the relatively-rare case …

DOCK-2126: Fix weird github apps lambda behavior

---

cloud-watch-to-slack-testing/deployment/index.js

Related to PR https://github.com/dockstore/dockstore-deploy/pull/542. This PR formats the message for an ssm session started by ECS Exec.
The message looks like: 
`arn:aws:sts::XXXXXXXXXXXX:assumed-role/AWSServiceRoleForECS/ecs-execute-command initiated AWS Systems Manager (SSM) event StartSession on Dockstore <env> in region: <region>. Event was initiated from IP [ecs.amazonaws.com](http://ecs.amazonaws.com/) to target: ecs:kathysJump-JumpEcsClusterDF384D0A-dqqEjUbMoybX_db1ecf00b04040f885e71369cdffeebf_db1ecf00b04040f885e71369cdffeebf-3189133771`
**Issue**
[SEAB-4501](https://ucsc-cgl.atlassian.net/browse/SEAB-4501)

Format message for ECS Exec

---

wdl-parsing/WDLParsingFunction/pom.xml

Seems like the broad artifactory changed locations. We build the lambda during the dockstore tests, so needed an update
**Issue**
https://github.com/dockstore/dockstore/pull/5622
**Security**

redirect pom

---

upsertGitHubTag/deployment/index.js

This PR extracts the GitHub App installation id from the event and passes it to the webservice delete webhook endpoint, which needs the installation id so it can connect to GitHub and check if the ref exists or not, as part of the implementation of https://ucsc-cgl.atlassian.net/browse/SEAB-5770
**Issue**
https://ucsc-cgl.atlassian.net/browse/SEAB-5770
**Security**

SEAB-5770: Propagate installationId to webservice delete webhook endpoint

---

cloud-watch-to-slack-testing/deployment/index.js

This PR modifies the "cloudwatch-to-slack" lambda to produce a "ecs task stopped" Slack message when it processes an event that indicates such.  The companion deploy PR, which modifies `DockstoreStack` to send the event to the associated SNS topic, is https://github.com/dockstore/dockstore-deploy/pull/746.
The Slack message looks like: https://ucsc-gi.slack.com/archives/C02DTE86E8J/p1705536998257129
Note that subsequently, I removed the `startedBy` field, it will rarely change and didn't seem worth the space.   We can nuke any of the other information if we don't think it is useful.
Charles mentions that it'd be useful to link items in this and other Slack messages to the appropriate AWS page.  So, I investigated, and it's certainly doable, but not as easy as pasting a …

SEAB-5860: Convert "ecs stopped task" event to Slack message

---

upsertGitHubTag/deployment/index.js
wdl-parsing/WDLParsingFunction/pom.xml

This PR changes the upsertGitHub lambda to propagate both possible varieties of the "installation_repositories" event (wherein the action is either "added" or "removed") to the webservice.
Regarding the code style, it's not how I would have formatted/indented the code, but that's what our tests require. 
Had remove the duplicate `<repository>` lines from that pom to make the tests pass.
After this PR merges, I will update `dockstore-deploy` to incorporate the corresponding commit.
**Review Instructions**
https://ucsc-cgl.atlassian.net/browse/SEAB-6000
**Testing**
See https://github.com/dockstore/dockstore/pull/5852
**Security**
No concerns.

SEAB-6000: Propagate both the "added" and "removed" varieties of the "installation_repositories" event

---

upsertGitHubTag/deployment/index.js

This PR adds code to the existing github lambda to send the message to a S3 bucket. The lambda uploads the event in the path `date/deliveryid`
**Issue**
https://ucsc-cgl.atlassian.net/browse/SEAB-5604
**Security**

SEAB-5604: submit github delivery event to s3

---

upsertGitHubTag/deployment/index.js

We noticed the events in the new github s3 bucket is creating folders with a wrong current date.
This was because the `getMonth` function is zero-index based so we have to add 1 to get the correct month.
**Issue**
https://ucsc-cgl.atlassian.net/browse/SEAB-5604
**Security**

SEAB-5604: fix date for the github lambda bucket

---

upsertGitHubTag/deployment/index.js

The folder names were messed up in the new s3 github delivery bucket because of the linter formatting.
Before:
After:
**Issue**
https://ucsc-cgl.atlassian.net/browse/SEAB-6405
**Security**

SEAB-6405: Fix date/folder formatting for github app delivery bucket

---

upsertGitHubTag/deployment/index.js

This PR changes the bucket key format to `YYYY-MM-DD/HH/deliveryid` instead of `YYYY-MM-DD/deliveryid` such that we can resubmit events by the hour
**Issue**
https://ucsc-cgl.atlassian.net/browse/SEAB-6452
**Security**

SEAB-6452: add hour to bucket key for GitHub redelivery

---

upsertGitHubTag/deployment/index.js

This PR adds the event type to the s3 bucket.
New format of events in bucket
```
{
"eventType": <"installation_repositories" or <"push">,
"body": {...}
}
```
**Issue**
https://ucsc-cgl.atlassian.net/browse/SEAB-6452
**Security**

SEAB-6452: add eventtype to s3

---

.circleci/config.yml
checkUrlExists/lambda/tests/unit/test-handler.js

A unit test started failing because the ICGC data portal was shut down.
Found a reasonably large file to replace the test with, although it's "only" 78M, compared to the previous file's 5.24GB.
The point of the test is to verify that a HEAD operation works, and while it's less than ideal, I think the file is big enough.
Also changed CircleCI build to use `npm ci` instead of `npm i`.
**Issue**
dockstore/dockstore#5935
DOCK-2548
**Security**

Change test to a different large file

---

cloud-watch-to-slack-testing/deployment/index.js

This PR displays the containers that belong to the task when an ECS task state change event is received by the lambda.
See the dockstore-deploy PR https://github.com/dockstore/dockstore-deploy/pull/816 that redirects the events to different channels depending on if it's for the webservice task or a scheduled task.
The notifications now look like this for the webservice task:
```
Task arn:aws:ecs:us-east-2:<account-id>:task/KathysDockstore-DockstoreEcsCluster36A20B87-GI07lGcyBwKc/0d9fe1faba344695b0ad6fa00a3a5d0d is now STOPPED
Containers: bootstrap, webservice, cloudwatch-agent, migration, nginx
startedAt: 2024-12-10T18:04:28.393Z
stoppedAt: 2024-12-10T18:09:33.907Z
stoppedReason: Task stopped by user
```
and the topic updater task:
```
Task …
```

Display task container names for ECS task state change events
